from sqlalchemy import (
    CHAR,
    BigInteger,
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    MetaData,
    SmallInteger,
    String,
    Table,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, INET, UUID

from app.db.base import NAMING_CONVENTION

metadata = MetaData(naming_convention=NAMING_CONVENTION)

users = Table(
    "users",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("email", String, nullable=False),
    Column("email_verified_at", DateTime(timezone=True)),
    Column("display_name", String(80), nullable=False),
    Column("password_hash", String(255)),
    Column("role", String(20), nullable=False),
    Column("locale", String(10), nullable=False),
    Column("timezone", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("deleted_at", DateTime(timezone=True)),
    Column("last_login_at", DateTime(timezone=True)),
)

refresh_tokens = Table(
    "refresh_tokens",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("user_id", UUID(as_uuid=True), ForeignKey("users.id"), nullable=False),
    Column("token_hash", CHAR(64), nullable=False),
    Column("family_id", UUID(as_uuid=True), nullable=False),
    Column("parent_id", UUID(as_uuid=True), ForeignKey("refresh_tokens.id")),
    Column("user_agent", String(255)),
    Column("ip_address", INET),
    Column("issued_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True)),
    Column("used_at", DateTime(timezone=True)),
)

imports = Table(
    "imports",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("user_id", UUID(as_uuid=True), ForeignKey("users.id"), nullable=False),
    Column("original_filename", String(255), nullable=False),
    Column("file_size_bytes", BigInteger, nullable=False),
    Column("file_hash", CHAR(64), nullable=False),
    Column("storage_key", String(500), nullable=False),
    Column("source", String(40), nullable=False),
    Column("language", String(10), nullable=False),
    Column("status", String(20), nullable=False),
    Column("total_hands_detected", Integer),
    Column("total_hands_imported", Integer),
    Column("total_hands_duplicate", Integer),
    Column("total_errors", Integer),
    Column("started_at", DateTime(timezone=True)),
    Column("finished_at", DateTime(timezone=True)),
    Column("error_message", Text),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

import_errors = Table(
    "import_errors",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("import_id", UUID(as_uuid=True), ForeignKey("imports.id"), nullable=False),
    Column("line_start", Integer, nullable=False),
    Column("line_end", Integer, nullable=False),
    Column("raw_excerpt", Text, nullable=False),
    Column("error_code", String(60), nullable=False),
    Column("error_message", Text, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

sessions = Table(
    "sessions",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("user_id", UUID(as_uuid=True), ForeignKey("users.id"), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("ended_at", DateTime(timezone=True), nullable=False),
    Column("total_hands", Integer, nullable=False),
    Column("net_profit_cents", BigInteger, nullable=False),
    Column("currency", CHAR(3), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

hands = Table(
    "hands",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("user_id", UUID(as_uuid=True), ForeignKey("users.id"), nullable=False),
    Column("import_id", UUID(as_uuid=True), ForeignKey("imports.id"), nullable=False),
    Column("session_id", UUID(as_uuid=True), ForeignKey("sessions.id")),
    Column("site", String(40), nullable=False),
    Column("site_hand_id", String(40), nullable=False),
    Column("site_tournament_id", String(40)),
    Column("site_table_name", String(80), nullable=False),
    Column("game_type", String(20), nullable=False),
    Column("variant", String(20), nullable=False),
    Column("table_max_players", SmallInteger, nullable=False),
    Column("buy_in_cents", BigInteger),
    Column("fee_cents", BigInteger),
    Column("currency", CHAR(3), nullable=False),
    Column("level_name", String(20)),
    Column("small_blind", BigInteger, nullable=False),
    Column("big_blind", BigInteger, nullable=False),
    Column("ante", BigInteger, nullable=False),
    Column("button_seat", SmallInteger, nullable=False),
    Column("hero_seat", SmallInteger),
    Column("hero_username", String(60), nullable=False),
    Column("played_at", DateTime(timezone=True), nullable=False),
    Column("timezone_at_play", String(40)),
    Column("board_cards", ARRAY(String(2)), nullable=False),
    Column("pot_total", BigInteger, nullable=False),
    Column("rake", BigInteger, nullable=False),
    Column("hero_position", String(8)),
    Column("hero_starting_stack", BigInteger),
    Column("hero_hole_cards", ARRAY(String(2))),
    Column("hero_net_cents", BigInteger),
    Column("hero_went_to_showdown", Boolean, nullable=False),
    Column("hero_won_at_showdown", Boolean),
    Column("h_saw_flop", Boolean, nullable=False),
    Column("h_saw_turn", Boolean, nullable=False),
    Column("h_saw_river", Boolean, nullable=False),
    Column("h_went_to_sd", Boolean, nullable=False),
    Column("h_won_at_sd", Boolean, nullable=False),
    Column("h_vpip", Boolean, nullable=False),
    Column("h_pfr", Boolean, nullable=False),
    Column("h_three_bet", Boolean, nullable=False),
    Column("h_faced_three_bet", Boolean, nullable=False),
    Column("h_folded_to_three_bet", Boolean, nullable=False),
    Column("h_pf_open", Boolean, nullable=False),
    Column("h_postflop_bets", SmallInteger, nullable=False),
    Column("h_postflop_raises", SmallInteger, nullable=False),
    Column("h_postflop_calls", SmallInteger, nullable=False),
    Column("raw_text", Text, nullable=False),
    Column("parser_version", String(20), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

hand_players = Table(
    "hand_players",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("hand_id", UUID(as_uuid=True), ForeignKey("hands.id"), nullable=False),
    Column("seat", SmallInteger, nullable=False),
    Column("username", String(60), nullable=False),
    Column("starting_stack", BigInteger, nullable=False),
    Column("position", String(8)),
    Column("is_hero", Boolean, nullable=False),
    Column("sit_out", Boolean, nullable=False),
    Column("posted_blind", String(10)),
    Column("blind_amount", BigInteger, nullable=False),
    Column("hole_cards", ARRAY(String(2))),
    Column("went_to_showdown", Boolean, nullable=False),
    Column("won_amount", BigInteger, nullable=False),
    Column("final_action_street", String(10)),
)

actions = Table(
    "actions",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("hand_id", UUID(as_uuid=True), ForeignKey("hands.id"), nullable=False),
    Column("user_id", UUID(as_uuid=True), nullable=False),
    Column("player_id", UUID(as_uuid=True), ForeignKey("hand_players.id"), nullable=False),
    Column("sequence", Integer, nullable=False),
    Column("street", String(10), nullable=False),
    Column("action_type", String(20), nullable=False),
    Column("amount", BigInteger, nullable=False),
    Column("raise_to", BigInteger),
    Column("is_all_in", Boolean, nullable=False),
    Column("pot_before", BigInteger, nullable=False),
    Column("pot_after", BigInteger, nullable=False),
)

pots = Table(
    "pots",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v7()")),
    Column("hand_id", UUID(as_uuid=True), ForeignKey("hands.id"), nullable=False),
    Column("pot_index", SmallInteger, nullable=False),
    Column("amount", BigInteger, nullable=False),
    Column("rake", BigInteger, nullable=False),
    Column("winners", ARRAY(UUID(as_uuid=True)), nullable=False),
)
