name: Feature request
description: Proponha uma melhoria ou funcionalidade.
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Qual problema do usuario isso resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceite
